application: lamthierry
version: 12
runtime: python
api_version: 1

handlers:
- url: /load
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /media
  static_dir: media

- url: /.*
  script: main.py
